name: Docker Image CI

on:
  push:
    branches: [ main2 ]
  pull_request:
    branches: [ main2 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jinmok:$(date +%s)
    - name: Veracode Upload And Scan
      # You may pin to the exact commit or the version.
      # uses: veracode/veracode-uploadandscan-action@c1ac3694a8ecfbe360fa7ae0b7e1367256259501
      uses: veracode/veracode-uploadandscan-action@0.2.2
        with:
      # appname
      appname: ${{ github.repository }}
      # createprofile
      createprofile: true # default is true
      # filepath
      filepath: 
        # version
        version: # default is Scan from Github job: ${{ github.run_id }}-${{ github.run_number }}
        # vid
        vid: ${{ VERACODE_API_ID }}
        # vkey
        vkey: ${{ VERACODE_API_KEY }}
        # true or flase
        createsandbox: true # optional
        # name of the sandbox
        sandboxname: sandyOne # optional
        # wait X minutes for the scan to complete
        #scantimeout: # optional
        # modules to exclude from module selection
        #exclude: # optional
        # modules to include in module selection
        #include: # optional
        # business criticality - policy selection
        criticality: "Very High"# optional
        # filename pattern
#        pattern: # optional
        # replacement
 #       replacement: # optional
        # specify to scan in a sandbox
 #       sandboxid: # optional
        # All top level modules
 #       scanallnonfataltoplevelmodules: # optional
        # platform selected modules
 #       selected: # optional
        # selected modules like from previous scan
 #       selectedpreviously: # optional
        # teams
 #       teams: # optional
        # teams
 #       toplevel: # optional
        # automatically delete the current scan if there are any errors when uploading files or starting the scan
 #       deleteincompletescan: # optional
